### ISSUE TITLE
Browser always opens with inspector open by default

### ISSUE THREAD

**Issue by morgane** [nickbytes/nabu#1]
When I run `yarn start`, the browser opens with the inspector panel. We don't want this.

<img width="1134" alt="screen shot 2018-10-20 at 5 50 08 pm" src="https://user-images.githubusercontent.com/104024/47262005-9a113c00-d490-11e8-9ecf-79dc1eed07ab.png">

**Comment by nickbytes** [comment]
I believe this only happens because you are in [development mode](https://github.com/nickbytes/nabu/blob/master/src/index.ts#L30), and once we build/package the app, will will not be visible. 

Imma close this now, but if its annoying we can create a property to toggle to specify while in development mode still.

**Comment by morgane** [comment]
Ohh gotcha. Sounds good 👍
